name: "release"

on:
  push:
    tags:
      - '*'

jobs:
  push_to_registry:
    name: Push docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag l7mp/net-debug:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push l7mp/net-debug:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag l7mp/net-debug:latest
      - name: Push the latest Docker image
        run: docker push l7mp/net-debug:latest
